name: Auto-Update Feed

on:
  schedule:
    - cron: '0 5 * * *' # Ogni giorno alle 5:00 AM UTC (7:00 AM IT)
  workflow_dispatch: # Permette avvio manuale

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Feed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull
          git add .
          git commit -m "Auto-update feed"
          git push
